### ISSUE TITLE
Overlap flexbox

### ISSUE THREAD

**Issue by MiloVanderpooten** [zavo-web/spotify-web-replica-MiloVanderpooten#1]
Wanneer ik geen flexbox toevoeg aan mijn main, komen sommige elementen zonder reden naast elkaar te staan, wanneer ik flexbox toevoeg overlappen de elementen met elkaar tenzij ik wrap toevoeg maar dan komen er weer elementen naast elkaar te staan.

**Comment by sarabarrerariano-zavo** [comment]
Is in orde nu nee?
